# Generated by Django 3.2.8 on 2021-11-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/listings/%y/%m/%d/'),
        ),
    ]
